name: Snapshot Release

on:
  issue_comment:
    types:
      - created

jobs:
  release_next:
    name: release:next
    runs-on: ubuntu-latest
    # Permissions necessary for Changesets to push a new branch and open PRs
    # (for automated Version Packages PRs), and request the JWT for provenance.
    # More info: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#adding-permissions-settings
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    if: |
      github.repository == 'jerelmiller/actions-testing' &&
      github.event.issue.pull_request &&
      (
        github.event.sender.login == 'benjamn' ||
        github.event.sender.login == 'alessbell' ||
        github.event.sender.login == 'bignimbus' ||
        github.event.sender.login == 'hwillson' ||
        github.event.sender.login == 'jerelmiller' ||
        github.event.sender.login == 'phryneas'
      ) &&
      startsWith(github.event.comment.body, '/release:pr')

    steps:
      - uses: alessbell/pull-request-comment-branch@v1.1
        id: comment-branch

      - name: Get sha
        id: parse-sha
        run: |
          if (
            ${{ github.event.sender.login }} == 'benjamn' ||
            ${{ github.event.sender.login }} == 'alessbell' ||
            ${{ github.event.sender.login }} == 'bignimbus' ||
            ${{ github.event.sender.login }} == 'hwillson' ||
            ${{ github.event.sender.login }} == 'jerelmiller' ||
            ${{ github.event.sender.login }} == 'phryneas'
          ); then
            echo "sha<<${{ steps.comment-brand.outputs.head_sha }}" >> "${GITHUB_OUTPUT}"
          else
            echo "sha<<"${${{ github.event.comment.body }} | tr -s ' ' | cut -d ' ' -f2}" >> "${GITHUB_OUTPUT}"
          fi

      - name: Checkout head ref
        uses: actions/checkout@v4
        with:
          ## specify the owner + repository in order to checkout the fork
          ## for community PRs
          repository: ${{ steps.comment-branch.outputs.head_owner }}/${{ steps.comment-branch.outputs.head_repo }}
          ref: ${{ steps.parse-sha.outputs.sha }}
          fetch-depth: 0

      - name: Detect new changesets
        id: added-files
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "changesets<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$(git diff --name-only --diff-filter=A ${{ steps.comment-branch.outputs.base_sha }} ${{ steps.parse-sha.outputs.sha }} .changeset/*.md)" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"

      # - name: Create comment
      #   if: ${{ steps.added-files.outputs.changesets != '' }}
      #   uses: peter-evans/create-or-update-comment@v4.0.0
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       A new release has been made for this PR. You can install it with:
      #
      #       ```
      #       npm i @apollo/client@${{ steps.get-version.outputs.version }}
      #       ```
      #
